labels:
  - "Loaded Language"
  - "Name Calling, Labeling"
  - "Repetition"
  - "Exaggeration, Minimization"
  - "Doubt"
  - "Appeal to Fear/Prejudice"
  - "Flag-Waving"
  - "Causal Oversimplification"
  - "Slogans"
  - "Appeal to Authority"
  - "Black-and-White Fallacy"
  - "Thought-terminating Cliches"
  - "Bandwagon, Reductio ad Hitlerum"
  - "Straw Men, Whataboutism, Red Herring"